// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvefq_HEXtSrYxtp-XCxYSlfw-u0ESXNY',
    appId: '1:255550956107:web:c58913332046558d9be3ce',
    messagingSenderId: '255550956107',
    projectId: 'gaigai-b4b88',
    authDomain: 'gaigai-b4b88.firebaseapp.com',
    storageBucket: 'gaigai-b4b88.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY-DB0EJwvqG04bDwrW436kwK7PSCfcLw',
    appId: '1:255550956107:android:281920c657bbaac69be3ce',
    messagingSenderId: '255550956107',
    projectId: 'gaigai-b4b88',
    storageBucket: 'gaigai-b4b88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDONziPOcJW_trVjBW0CrsNbjy75JtL1qg',
    appId: '1:255550956107:ios:31a83fcee2417d889be3ce',
    messagingSenderId: '255550956107',
    projectId: 'gaigai-b4b88',
    storageBucket: 'gaigai-b4b88.firebasestorage.app',
    iosBundleId: 'com.example.gaigai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDONziPOcJW_trVjBW0CrsNbjy75JtL1qg',
    appId: '1:255550956107:ios:31a83fcee2417d889be3ce',
    messagingSenderId: '255550956107',
    projectId: 'gaigai-b4b88',
    storageBucket: 'gaigai-b4b88.firebasestorage.app',
    iosBundleId: 'com.example.gaigai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvefq_HEXtSrYxtp-XCxYSlfw-u0ESXNY',
    appId: '1:255550956107:web:d45d275b894482f79be3ce',
    messagingSenderId: '255550956107',
    projectId: 'gaigai-b4b88',
    authDomain: 'gaigai-b4b88.firebaseapp.com',
    storageBucket: 'gaigai-b4b88.firebasestorage.app',
  );

}