// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotWFXuaJCugD16OIS-49Q5xSOaLKy7wc',
    appId: '1:470203659026:web:de2d42ffc68184a1de39cb',
    messagingSenderId: '470203659026',
    projectId: 'gaigai-apac-solution-challenge',
    authDomain: 'gaigai-apac-solution-challenge.firebaseapp.com',
    storageBucket: 'gaigai-apac-solution-challenge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO1_C8_NVmf-KAlg73v-uE_xSIo7CGPoA',
    appId: '1:470203659026:android:ad1bb3b8ec41053fde39cb',
    messagingSenderId: '470203659026',
    projectId: 'gaigai-apac-solution-challenge',
    storageBucket: 'gaigai-apac-solution-challenge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqdF3hIHVE8qwvAIjmrqRYEc3KhfIae38',
    appId: '1:470203659026:ios:af43384ef346cb06de39cb',
    messagingSenderId: '470203659026',
    projectId: 'gaigai-apac-solution-challenge',
    storageBucket: 'gaigai-apac-solution-challenge.firebasestorage.app',
    iosBundleId: 'com.example.gaigai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqdF3hIHVE8qwvAIjmrqRYEc3KhfIae38',
    appId: '1:470203659026:ios:af43384ef346cb06de39cb',
    messagingSenderId: '470203659026',
    projectId: 'gaigai-apac-solution-challenge',
    storageBucket: 'gaigai-apac-solution-challenge.firebasestorage.app',
    iosBundleId: 'com.example.gaigai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBotWFXuaJCugD16OIS-49Q5xSOaLKy7wc',
    appId: '1:470203659026:web:9f533bdcbc5fe174de39cb',
    messagingSenderId: '470203659026',
    projectId: 'gaigai-apac-solution-challenge',
    authDomain: 'gaigai-apac-solution-challenge.firebaseapp.com',
    storageBucket: 'gaigai-apac-solution-challenge.firebasestorage.app',
  );

}
